version: '3'
services: 
    registers-db:
        build: ./microServices/registers/db
        volumes:
            - ./microServices/registers/db/data:/data/db
        networks:
            - registers-network
    registers-service:
        build: ./microServices/registers/service
        depends_on:
            - registers-db
        networks:
            - registers-network
        tty: true
        stdin_open: true
    teachers-db:
        build: ./microServices/teachers/db
        volumes: 
            - ./microServices/teachers/db/data:/data/db
        networks:
            - teachers-network
    teachers-service:
        build: ./microServices/teachers/service
        depends_on:
            - teachers-db
        networks:
            - teachers-network
        tty: true
        stdin_open: true
    attendances-db:
        build: ./microServices/attendances/db
        volumes: 
            - ./microServices/attendances/db/data:/data/db
        networks:
            - attendances-network
    attendances-service:
        build: ./microServices/attendances/service    
        depends_on:
            - attendances-db
        networks:
            - attendances-network
        tty: true
        stdin_open: true
    wrapper:
        build: ./wrapper
        depends_on:
            - registers-service
            - teachers-service
            - attendances-service
        tty: true
        stdin_open: true

networks:
  registers-network:
  attendances-network:
  teachers-network: